# Generated by Django 4.1.2 on 2024-04-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, verbose_name='video_id')),
                ('video_title', models.CharField(max_length=100, verbose_name='動画タイトル')),
                ('chapter_title', models.CharField(max_length=100, unique=True, verbose_name='チャプタータイトル')),
                ('chapter_url', models.CharField(max_length=100, verbose_name='チャプターURL')),
                ('published_date', models.DateField(verbose_name='配信日')),
            ],
        ),
    ]
