# Generated by Django 4.1.2 on 2024-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterinfo',
            name='chapter_title',
            field=models.CharField(max_length=100, verbose_name='チャプタータイトル'),
        ),
    ]
