# Generated by Django 4.1.2 on 2024-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_chapterinfo_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterinfo',
            name='chapter_start',
            field=models.CharField(default=0, max_length=100, verbose_name='チャプター開始時間'),
            preserve_default=False,
        ),
    ]
