# Generated by Django 4.1.2 on 2025-05-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chapterinfo_chapter_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, verbose_name='video_id')),
                ('video_title', models.CharField(max_length=100, verbose_name='動画タイトル')),
                ('published_date', models.DateField(verbose_name='配信日')),
            ],
        ),
    ]
