# Generated by Django 4.1.2 on 2025-05-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_videoinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='video_url',
            field=models.CharField(default='', max_length=100, verbose_name='動画URL'),
            preserve_default=False,
        ),
    ]
